CREATE TABLE IF NOT EXISTS boards(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    removed BOOL NOT NULL DEFAULT FALSE,
    number INTEGER NOT NULL,
    dealer VARCHAR(1) NOT NULL,
    vulnerable VARCHAR(3) NOT NULL CHECK (vulnerable IN ('NS', 'EW', 'ALL', '-'))
);

CREATE TABLE IF NOT EXISTS users(
                                    id UUID PRIMARY KEY,
                                    created_at TIMESTAMP NOT NULL,
                                    updated_at TIMESTAMP NOT NULL,
                                    removed BOOL NOT NULL DEFAULT FALSE,
                                    name VARCHAR(30),
    surname VARCHAR(30),
    username VARCHAR(30) NOT NULL,
    sport_category NUMERIC(2, 1) CHECK (sport_category >= -5.0 AND sport_category <= 5.0)
    );

CREATE TABLE IF NOT EXISTS tournaments(
                                          id UUID PRIMARY KEY,
                                          created_at TIMESTAMP NOT NULL,
                                          updated_at TIMESTAMP NOT NULL,
                                          removed BOOL NOT NULL DEFAULT FALSE,
                                          owner_id UUID REFERENCES users(id) NOT NULL,
    count_type VARCHAR(20),
    boards INTEGER NOT NULL CHECK (boards > 0),
    rounds INTEGER,
    name TEXT,
    started BOOL
    );

CREATE TABLE IF NOT EXISTS tournament_tds(
                                             tournament_id UUID REFERENCES tournaments(id) NOT NULL,
    td_id UUID REFERENCES users(id) NOT NULL,
    PRIMARY KEY (tournament_id, td_id)
    );

CREATE TABLE IF NOT EXISTS tournament_boards(
                                                tournament_id UUID REFERENCES tournaments(id) NOT NULL,
    board_id INTEGER REFERENCES boards(id) NOT NULL,
    PRIMARY KEY (tournament_id, board_id)
    );

CREATE TABLE IF NOT EXISTS pairs(
                                    id UUID PRIMARY KEY,
                                    first_player_id UUID REFERENCES users(id),
    second_player_id UUID REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS board_entries(
                                            id UUID PRIMARY KEY,
                                            created_at TIMESTAMP NOT NULL,
                                            updated_at TIMESTAMP NOT NULL,
                                            removed BOOL NOT NULL DEFAULT FALSE,
                                            board_id INTEGER REFERENCES boards(id) NOT NULL,
    writer_id UUID REFERENCES users(id) NOT NULL,
    ns UUID REFERENCES pairs(id),
    ew UUID REFERENCES pairs(id),
    contract VARCHAR(6) NOT NULL,
    declarer VARCHAR(1),
    lead VARCHAR(3),
    result INTEGER NOT NULL,
    UNIQUE (board_id, writer_id)
    );

CREATE TABLE IF NOT EXISTS users_current(
                                            user_id UUID PRIMARY KEY REFERENCES users(id),
    td UUID REFERENCES tournaments(id),
    player UUID REFERENCES tournaments(id)
    );

CREATE TABLE IF NOT EXISTS tournament_nodes(
                                               id UUID PRIMARY KEY,
                                               tournament_id UUID REFERENCES tournaments(id) NOT NULL,
    round INTEGER NOT NULL,
    "table" INTEGER NOT NULL,
    ns UUID REFERENCES pairs(id) NOT NULL,
    ew UUID REFERENCES pairs(id) NOT NULL
    );

CREATE TABLE IF NOT EXISTS tournament_node_entries(
    board_entry_id UUID REFERENCES board_entries(id) NOT NULL,
    node_id UUID REFERENCES tournament_nodes(id) NOT NULL,
    PRIMARY KEY (board_entry_id, node_id)
    );

CREATE TABLE IF NOT EXISTS tournament_node_boards(
                                                     node_id UUID REFERENCES tournament_nodes(id) NOT NULL,
    board_number INTEGER NOT NULL,
    PRIMARY KEY (node_id, board_number)
    );

CREATE TABLE IF NOT EXISTS tournament_players(
                                                 player_id UUID REFERENCES users(id) NOT NULL,
    tournament_id UUID REFERENCES tournaments(id) NOT NULL,
    PRIMARY KEY (player_id, tournament_id)
    );

CREATE TABLE IF NOT EXISTS tournamens_pairs(
                                               pair_id UUID REFERENCES pairs(id) NOT NULL,
    tournament_id UUID REFERENCES tournaments(id) NOT NULL,
    PRIMARY KEY (pair_id, tournament_id)
    );

CREATE TABLE movements(
                          id UUID PRIMARY KEY,
                            "type" VARCHAR(20),
                          rounds_count INTEGER NOT NULL,
                          pairs_count INTEGER NOT NULL,
                          body TEXT NOT NULL
);







